#Ejercicio de Pandas:

Usa los dos archivos csv de la carpeta para completar las tareas que aparecen en negrita a continuación, responder sólo en la línea que aparece.

**Usar una celda de código**

Importar pandas and leer el archivo banklist.csv en una estructura de dataframe llamada bancos.

**Muestre las 10 primeras filas del dataframe**

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,1-Jun-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,1-Jun-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,23-May-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
5,Harvest Community Bank,Pennsville,NJ,34951,First-Citizens Bank & Trust Company,13-Jan-17,18-May-17
6,Allied Bank,Mulberry,AR,91,Today's Bank,23-Sep-16,17-Nov-16
7,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,19-Aug-16,1-Jun-17
8,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,6-May-16,6-Sep-16
9,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,29-Apr-16,6-Sep-16

**Imprima el nombre de las columnas**

TypeError: 'Index' object is not callable

**Obtener una lista o matriz de todos los estados en el conjunto de datos, sin repetición, ordenados de la A a la Z**

In [2]:
lista_estados = sorted(bancos['ST'].unique())
print(lista_estados)

NameError: name 'bancos' is not defined

**¿Cuáles son los 5 estados con más bancos fallidos?**

> Añadir blockquote

> Añadir blockquote

**¿Cuáles son las 5 principales instituciones adquirentes?**

**¿Cuántos bancos ha adquirido el State Bank of Texas? ¿Cuántos de ellos estaban realmente en Texas?**

**¿Cuál es la ciudad más común en California donde un banco quiebra?**

> Añadir blockquote

**¿Cuántos nombres de bancos comienzan con la letra 's'?**

**¿Cuántos bancos consisten en dos palabras? Ej. "First Bank" , "Bank Georgia"**

**¿Cuántos bancos quebrados no tienen la palabra "Banco" en su nombre?**

**¿Cuántos bancos cerraron en el año 2008?**

Hc